version: '3.3'

services:
  db:
    image: atfuentess/qa-automation:db_automation
    volumes:
      - db_data:/var/lib/mysql
      - ./ecommerce-app/data:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    volumes:
      - ./ecommerce-app/app:/var/www/html
      - ./ecommerce-app/data/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    depends_on:
      - db
    image: atfuentess/qa-automation:wordpress_automation
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  cypress:
    image: $CI_REGISTRY_IMAGE:cypress
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.json:/app/cypress.json
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./node_modules/:/app/node_modules/
    depends_on:
      - wordpress
      - db
    environment:
      - CYPRESS_baseUrl=http://wordpress
      - CYPRESS_username=automation
      - CYPRESS_password=automation

volumes:
    db_data: {}
    wp_files: {}
